add max footer logo size and add srta to loginpage
ManhanGroup/calbuilds pull request #134
Opened 2023-10-25 05:36 UTC by purpleplum

Resolves # .

# Why is this change necessary?
Issue #57 reopened and SRTA request

# How does it address the issue?
Add max width in css
# What side effects does it have?
None

2023-10-25 14:29 UTC, kaden-weber requested changes

2023-10-25 14:29 UTC, kaden-weber commented on ember/app/styles/routes/map.scss
> +        //min-height: fit-content;
Remove commented styles

2023-10-26 03:33 UTC, purpleplum commented on ember/app/styles/routes/map.scss
> +        //min-height: fit-content;
Removed.

2023-10-31 02:10 UTC, kaden-weber approved these changes

2023-10-31 02:10 UTC, merged